### ISSUE TITLE
Tags for recent versions are missing

### ISSUE THREAD

**Issue by IzzySoft** [ManojMadanmohan/dlt#11]
The last tag [here in releases/](https://github.com/ManojMadanmohan/dlt/releases) is for version 2.3.6 – while at playstore there are also 2.4.0 and 2.4.2. Could you please add the missing tags (and the APKs)? Thanks!

**Comment by ManojMadanmohan** [comment]
Hey Izzy,

Sure, will do.

**Comment by IzzySoft** [comment]
Thanks a lot! Please update this issue when done so I know I when can find them :smiley:

**Comment by ManojMadanmohan** [comment]
@IzzySoft this is done.

**Comment by IzzySoft** [comment]
Great, and thanks again!
