### ISSUE TITLE
Show and/or export list of all handlers?

### ISSUE THREAD

**Issue by UNIVAC-Colonel-Panic** [ManojMadanmohan/dlt#12]
Hi,

Is there a way to generate a list of all protocol handlers installed on an Android device?

**Comment by ManojMadanmohan** [comment]
You'll have to parse the manifests of all other apps

Some apps on play store used to do this - manifest readers

**Comment by UNIVAC-Colonel-Panic** [comment]
Thanks for your prompt reply! I didn't know about manifest readers so thanks for that tip.
