### ISSUE TITLE
Add Releases with apk

### ISSUE THREAD

**Issue by wispborne** [ManojMadanmohan/dlt#5]
Just a thought, would be nice to be able to download the apk file directly from github since emulators don't come with the Play Store installed.

Also, consider removing the keystore from git and doing a force push to pretend it was never there. If it's the release keystore, there's the chance someone could use it to publish your app as if it came from you.

Thanks for making this, I'm going to compile it myself and try it out now!

**Comment by ManojMadanmohan** [comment]
Hi David,

Thank you for your interest. Sorry for the late reply, I didn't check my personal mails last week.

I was keeping the release apks locally with me till now. Will start publishing them tonight. 

As for the keystore, it is password-protected. Should that be enough to prevent misuse?

**Comment by ManojMadanmohan** [comment]
I've added a release for the latest version. 

I will be following this as a practice from now on
